owner: PeriheliaSoftworks # Your GitHub organization or username, where this repository lives
repo: cadence-status # The name of this repository

sites:
  - name: Test Environment
    url: https://test.cadencebot.net/heatlhcheck

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.cadencebot.net
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Cadence
  introTitle: "Welcome to the **Cadence** status page."
  introMessage: All incidents and status updates affecting the Cadence service will be shown here.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
