owner: PeriheliaSoftworks
repo: cadence-status

user-agent: ZakFarmer

sites:
  - name: Test Environment
    url: https://test.cadencebot.net/healthcheck

  - name: Live Environment
    url: https://cadencebot.net/healthcheck

status-website:
  cname: status.cadencebot.net
  logoUrl: https://raw.githubusercontent.com/PeriheliaSoftworks/cadence-status/master/assets/cadence-icon-monotone.png
  name: Cadence
  introTitle: "Welcome to the **Cadence** status page."
  introMessage: Incidents and status updates affecting the Cadence service will be shown here.
  navbar:
    - title: Status
      href: /

i18n:
  footer: ""
